### ISSUE TITLE
sound issue

### ISSUE THREAD

**Issue by driouach88** [FiveM-Scripts/nightclubs#2]
whenever you leave the club . you have no sound . would be cool if the monitors and smoke effect are added as well . gr8 job bro

**Comment by ghermans** [comment]
- Strange that you have no sound when leaving the nightclub (i will need to do some testing to know what is going on)
- The monitors have already been added and will be available in the next update.
- i will take a look to add the smoke effects

**Comment by driouach88** [comment]
the gun shots and weapon sounds dont work .its weird but for some reason it stops working until i stop the resource .thks for your reply . cant wait for the monitors update

**Comment by ghost** [comment]
Im having the exact same issue right now.Any update?

**Comment by killaway** [comment]
Hi, also having the same issue, any update? Would be great to get this working. Thanks

**Comment by killaway** [comment]
Is this fixed?

**Comment by ghermans** [comment]
Yes, a new release has been added  https://github.com/FiveM-Scripts/nightclubs/releases/latest

**Comment by ghermans** [comment]
update: just had to push the release again as the previous push failed to get the latest files.  this should be resolved now.

**Comment by killaway** [comment]
Brilliant thanks mate. Great work
