### ISSUE TITLE
How i can add ped with animation?

### ISSUE THREAD

**Issue by Zaagris** [FiveM-Scripts/nightclubs#3]
Hello all! Can somebody help with this im trying everything but still not working/

**Comment by AdaModz** [comment]
example": 
ymapPedTab = ymapPedTab or {}
ymapVehTab = ymapVehTab or {}

ymapPedTab = {
        {-27.5472832, -1675.289, 29.5099926, 129.995834, -2018356203, 'ANIME OR SCENARIO', 0, 'Unarmed', 'PED HASH'},
}
